### ISSUE TITLE
Lolicon API的色图

### ISSUE THREAD

**Issue by poly000** [yuyuziYYZ/skadi_bot#1]
https://api.lolicon.app/#/

**Comment by yuyuziYYZ** [comment]
是这样的，基于lolicon api的涩图，不过后续涩图功能应该就停更了（账号一天冻结两次，已经关掉涩图了

**Comment by poly000** [comment]
> 是这样的，基于lolicon api的涩图，不过后续涩图功能应该就停更了（账号一天冻结两次，已经关掉涩图了

啊这…… 私聊也不行吗？
要不要考虑只发送pixiv cat链接？

**Comment by yuyuziYYZ** [comment]
r18的图需要使用【色图】命令而不是涩图，只发送链接以前尝试过，但是还是会封号，所以我已经准备停更掉涩图功能，不过现在版本依旧可以使用

**Comment by poly000** [comment]
r18已经完全在 #2 禁用
